[package]
name = "mattyb"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
axum-server = { version = "0.7.1", features = ["tls-rustls"] }
clap = { version = "4.4", features = ["derive"] }
log = "0.4.17"
rustls-acme = { version = "0.12.1", features = ["axum"] }
simple_logger = "5.0.0"
tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = "0.1.14"
